services:
  lazyvim_node_js:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GIT_TOKEN: ${GIT_TOKEN}
        GIT_USER: ${GIT_USER:-eliBrank}
        GIT_EMAIL: ${GIT_EMAIL}
    container_name: lazyvim_node_js
    entrypoint: ["sh", "-c", "sleep infinity"]
    init: true
    environment:
      - DISPLAY=${DISPLAY:-:0} # fallback to :0 if unset
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - GIT_TOKEN=${GIT_TOKEN:-}
      - GIT_USER=${GIT_USER:-eliBrank}
      - GIT_EMAIL=${GIT_EMAIL:-}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:ro
    devices:
      - /dev/dri
    stdin_open: true
    tty: true
    ports:
      - "5173:5173"  # default port for Vite
